name: iptvzby

# 触发条件
on:
  # 定时任务，每天 6 点 30 分和 22 点 30 分执行
  schedule:
    - cron: '30 6,22 * * *'
  # 当 main 分支有推送时触发
  push:
    branches:
      - main

# 权限设置
permissions:
  contents: write

# 任务定义
jobs:
  build:
    # 指定运行环境为最新的 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 检出代码步骤
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Python 环境步骤
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # 指定 Python 版本为 3.x
          python-version: 3.x

      # 安装依赖步骤
      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      # 运行 iptv 脚本步骤
      - name: Run iptv
        run: python ${{ github.workspace }}/iptvzby.py

      # 提交更改步骤
      - name: Commit and push if changed
        run: |
          # 设置 Git 用户邮箱
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          # 设置 Git 用户名称
          git config --local user.name "github-actions[bot]"
          # 查看当前更改
          git diff
          # 获取最终文件路径
          final_file=$(python -c '
          try: 
            import user_config as config
          except ImportError: 
            import config
          print(config.final_file)')

          # 如果暂存区有更改，则提交并强制推送
          if! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push --force
          fi
